# Generated by Django 5.0.7 on 2024-09-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Седан', 'Седан'), ('Купе', 'Купе'), ('Универсал', 'Универсал')], max_length=100, verbose_name='Тип машины'),
        ),
        migrations.CreateModel(
            name='CommentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rate_starts', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('car_choice_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_objects', to='car_shop.car')),
            ],
        ),
    ]
